### ISSUE TITLE
Incompatibility with Python2

### ISSUE THREAD

**Issue by paulmueller** [cimatosa/progress#2]
When trying to install from the repository using Python2, I get the following error:
`python setup.py install`

``` python
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from progression import __version__
  File "/home/paul/repos/progression/progression/__init__.py", line 62, in <module>
    from .progress import *
  File "/home/paul/repos/progression/progression/progress.py", line 96, in <module>
    mp.set_start_method('spawn')
AttributeError: 'module' object has no attribute 'set_start_method'
```

**Comment by cimatosa** [comment]
should be solved now (64b34bd322a1efc1c6a3f60a1bb7b6a8a71ebc2d) and tested

additionally progression works with and all tests passing using "spawn" method to create a subprocess, this is needed for windows compatibility ;-)
